title: RangelPage
email: info@garcad.cat
author: Ramon Àngel Garcia Adell
description: A Jekyll blog with bootstrap
url: "http://localhost:4000"
baseUrl: "/"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

sass:
  sass_dir: _sass
  style: compressed
